<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="All.fs" />
    <Compile Include="Annotation.fs" />
    <Compile Include="Any.fs" />
    <Compile Include="AnyAttribute.fs" />
    <Compile Include="Appinfo.fs" />
    <Compile Include="Attribute.fs" />
    <Compile Include="AttributeGroup.fs" />
    <Compile Include="Choice.fs" />
    <Compile Include="ComplexContent.fs" />
    <Compile Include="ComplexType.fs" />
    <Compile Include="Documentation.fs" />
    <Compile Include="Element.fs" />
    <Compile Include="ComplexContentExtension.fs" />
    <Compile Include="SimpleContentExtension.fs" />
    <Compile Include="Field.fs" />
    <Compile Include="Group.fs" />
    <Compile Include="Import.fs" />
    <Compile Include="Include.fs" />
    <Compile Include="Key.fs" />
    <Compile Include="Keyref.fs" />
    <Compile Include="List.fs" />
    <Compile Include="Notation.fs" />
    <Compile Include="Redefine.fs" />
    <Compile Include="ComplexContentRestriction.fs" />
    <Compile Include="SimpleContentRestriction.fs" />
    <Compile Include="SimpleTypeRestriction.fs" />
    <Compile Include="Schema.fs" />
    <Compile Include="Selector.fs" />
    <Compile Include="Sequence.fs" />
    <Compile Include="SimpleContent.fs" />
    <Compile Include="SimpleType.fs" />
    <Compile Include="Union.fs" />
    <Compile Include="Unique.fs" />
  </ItemGroup>
</Project>